<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            ['id' => '1',
                'username'=>'clieclie',
                'name' => 'Nome',
                'password' => Hash::make('1WzXhkxB'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '2',
                'username'=>'orgaorga',
                'name' => NULL,
                'password' => Hash::make('1WzXhkxB'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'organizzatore@test.com',
                'surname'=> NULL,
                'nome_org'=>'Organizzatore',
                'data_nascita' => NULL],

            ['id' => '3',
                'username'=>'adminadmin',
                'name' => NULL,
                'password' => Hash::make('1WzXhkxB'),
                'piva' => NULL,
                'livello_utenza'=>'4',
                'email'=>'admin@test.com',
                'surname'=>NULL,
                'nome_org'=>NULL,
                'data_nascita' => NULL ],

            ['id' => '4',
                'username'=>'cliente001',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '5',
                'username'=>'cliente002',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '6',
                'username'=>'cliente003',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '7',
                'username'=>'cliente004',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '8',
                'username'=>'cliente005',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '9',
                'username'=>'cliente006',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '10',
                'username'=>'cliente007',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '11',
                'username'=>'cliente008',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '12',
                'username'=>'cliente009',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '13',
                'username'=>'cliente010',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '14',
                'username'=>'cliente011',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '15',
                'username'=>'cliente012',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '16',
                'username'=>'cliente013',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '17',
                'username'=>'cliente014',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '18',
                'username'=>'cliente015',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '19',
                'username'=>'cliente016',
                'name' => 'Nome',
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'2',
                'email'=>'cliente@test.com',
                'surname'=>'Cognome',
                'nome_org'=>NULL,
                'data_nascita' => '1990-01-01'],

            ['id' => '20',
                'username'=>'org01',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'org1@test.com',
                'surname'=>NULL,
                'nome_org'=>'Organizzatore 01',
                'data_nascita' => NULL ],

            ['id' => '21',
                'username'=>'org02',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'org2@test.com',
                'surname'=>NULL,
                'nome_org'=>'Organizzatore 02',
                'data_nascita' => NULL ],

            ['id' => '22',
                'username'=>'org03',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'org3@test.com',
                'surname'=>NULL,
                'nome_org'=>'Organizzatore 03',
                'data_nascita' => NULL ],

            ['id' => '23',
                'username'=>'org04',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'org3@test.com',
                'surname'=>NULL,
                'nome_org'=>'Organizzatore 04',
                'data_nascita' => NULL ],

            ['id' => '24',
                'username'=>'org05',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'org3@test.com',
                'surname'=>NULL,
                'nome_org'=>'Organizzatore 05',
                'data_nascita' => NULL ],

            ['id' => '25',
                'username'=>'org06',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'org3@test.com',
                'surname'=>NULL,
                'nome_org'=>'Organizzatore 06',
                'data_nascita' => NULL ],

            ['id' => '26',
                'username'=>'org07',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'org3@test.com',
                'surname'=>NULL,
                'nome_org'=>'Organizzatore 07',
                'data_nascita' => NULL ],

            ['id' => '27',
                'username'=>'org08',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'org3@test.com',
                'surname'=>NULL,
                'nome_org'=>'Organizzatore 08',
                'data_nascita' => NULL ],

            ['id' => '28',
                'username'=>'org09',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'org3@test.com',
                'surname'=>NULL,
                'nome_org'=>'Organizzatore 09',
                'data_nascita' => NULL ],

            ['id' => '29',
                'username'=>'org10',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => '123456789',
                'livello_utenza'=>'3',
                'email'=>'org3@test.com',
                'surname'=>NULL,
                'nome_org'=>'Organizzatore 10',
                'data_nascita' => NULL ],

            ['id' => '30',
                'username'=>'admin1',
                'name' => NULL,
                'password' => Hash::make('xxxxxxxx'),
                'piva' => NULL,
                'livello_utenza'=>'4',
                'email'=>'admin1@test.com',
                'surname'=> NULL,
                'nome_org'=>NULL,
                'data_nascita' => NULL],
        ]);

        DB::table('events')->insert([
            ['event_id'=> '1',
                'luogo' => 'Ancona, PalaRossini',
                'data'=> '2021-08-01',
                'ora'=>'18:00:00',
                'regione'=> 'Marche',
                'image_catalogo'=> '1.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'Dalla Stazione Ferroviaria di Passo Varano percorrere 500 metri in direzione dello Stadio. Dall\'Aereoporto Raffaello Sanzio di Falconara, imboccare la Superstrada in direzione Ancona Sud, seguire poi indicazioni per Impianti sportivi o Stadio del Conero. Autostrada A14: uscita Ancona Sud. Dopo il casello a destra per Ancona centro. Dopo circa 1,5 Km a destra seguire indicazioni per Stadio Conero / Palasport.',
                'artista' => 'Rkomi',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => (10000-126),
                'costo' => 25.00,
                'org_name' => 'Organizzatore 01',
                'descrizione' => 'Rkomi torna live dopo più di un anno per il suo concerto ad Ancona. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 70],

            ['event_id'=> '2',
                'luogo' => 'Roma, Stadio Olimpico',
                'data'=> '2021-08-01',
                'ora'=>'18:00:00',
                'regione'=> 'Lazio',
                'image_catalogo'=> '2.png',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'Dal Grande Raccordo Anulare (G.R.A.): muoviti verso l’uscita N° 6 Flaminia e segui le indicazioni per lo Stadio – Foro Italico. Dall’autostrada A1 (Milano-Bologna-Firenze): raggiungi il G.R.A. in direzione Flaminia e segui le indicazioni per lo Stadio. Dall’autostrada A24-A25 (Pescara-Teramo-L’Aquila): raggiungi il G.R.A. in direzione A1. Dall’autostrada A2 (Napoli): raggiungi il G.R.A. direzione A1. Dall’Aeroporto di Roma-Fiumicino Leonardo da Vinci: raggiungi il G.R.A. in direzione Cassia-Flaminia.',
                'artista' => 'Madame',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => (10000-42),
                'costo' => 24.00,
                'org_name' => 'Organizzatore 01',
                'descrizione' => 'Madame torna live dopo più di un anno per il suo concerto a Roma. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 70],

            ['event_id'=> '3',
                'luogo' => 'Milano, Stadio San Siro',
                'data'=> '2021-08-01',
                'ora'=>'18:00:00',
                'regione'=> 'Lombardia',
                'image_catalogo'=> '3.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'Arrivando da Torino (autostrada A4): dopo la barriera proseguire verso Venezia fino allo svincolo per Milano Certosa ; di qui seguire le indicazioni per lo stadio. Arrivando da Bologna , Firenze , Roma ( autostrada A1 ): imboccare la Tangenziale Ovest , uscendo allo svincolo per la Statale 11 ; di qui si raggiunge facilemente lo stadio. Arrivando da Bergamo , Verona , Venezia , Udine ( autostrade A4 ): dopo la barriera di Milano Est proseguire verso Torino fino allo svincolo per Milano Certosa ; di qui seguire le indicazioni per lo stadio. Arrivando da Como , Lecco , Svizzera ( autostrada A8 - A9 ): dopo la barriera proseguire verso Milano Certosa ; di qui seguire le indicazioni per lo stadio.',
                'artista' => 'Caparezza',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => (10000-28),
                'costo' => 23.00,
                'org_name' => 'Organizzatore 01',
                'descrizione' => 'Caparezza torna live dopo più di un anno per il suo concerto a Milano. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 70],

            ['event_id'=> '4',
                'luogo' => 'Napoli, Stadio San Paolo',
                'data'=> '2021-10-01',
                'ora'=>'18:00:00',
                'regione'=> 'Campania',
                'image_catalogo'=> '4.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'Dalla Stazione Centrale: Linea 152 ANM (in Piazza Garibaldi) in direzione Piazzale Tecchio. Dall\'aeroporto di Capodichino: Servizio Alibus dall\'Aeroporto a Piazza Garibaldi (fermata Alibus) e poi Servizio metropolitano F.S. Linea 2 con fermata Campi Flegrei. In auto prendere la Tangenziale, uscita Fuorigrotta.',
                'artista' => 'DrefGold',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => 10000,
                'costo' => 23.00,
                'org_name' => 'Organizzatore 01',
                'descrizione' => 'DrefGold torna live dopo più di un anno per il suo concerto a Napoli. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 10],

            ['event_id'=> '5',
                'luogo' => 'Reggio Emilia, Mapei Stadium',
                'data'=> '2021-11-01',
                'ora'=>'18:00:00',
                'regione'=> 'Emilia Romagna',
                'image_catalogo'=> '5.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'Giungendo alla Stazione Centrale, sita in Piazzale Marconi è possibile raggiungere il Mapei Stadium a piedi o con la linea urbana 5. In auto imboccare l’uscita Reggio Emilia dell’autostrada A1; dopo l’uscita seguire le indicazioni per il centro della città e poi quelle per Moncasale.',
                'artista' => 'Fulminacci',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => 10000,
                'costo' => 22.00,
                'org_name' => 'Organizzatore 02',
                'descrizione' => 'Fulminacci torna live dopo più di un anno per il suo concerto a Reggio Emilia. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 10],

            ['event_id'=> '6',
                'luogo' => 'Torino, Allianz Stadium',
                'data'=> '2021-12-01',
                'ora'=>'18:00:00',
                'regione'=> 'Piemonte',
                'image_catalogo'=> '6.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'In auto è consigliabile utilizzare il Parcheggio Caio Mario, poi prendere la linea 4 o 10. In tram è consigliabile usufruire delle linee 4, 10, 14, 17, 63.',
                'artista' => 'Ghali',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => 10000,
                'costo' => 24.00,
                'org_name' => 'Organizzatore 02',
                'descrizione' => 'Ghali torna live dopo più di un anno per il suo concerto a Torino. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 10],

            ['event_id'=> '7',
                'luogo' => 'Bari, Stadio San Nicola',
                'data'=> '2022-01-01',
                'ora'=>'18:00:00',
                'regione'=> 'Puglia',
                'image_catalogo'=> '7.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'Per arrivare al San Nicola in auto uscire dall\'Autostrada A14 a "Bari Nord/Bari Centro/Brindisi" e prendere la E55. Uscire a "Bari Centro/ Brindisi/ Lecce/ Taranto" e poi prendere l\'uscita 10A "Bari Picone/ Via Bitritto/ Policlinico". Prendere la SS271, girare a destra in Via Privata di Santa Fara e poi in Strada Torre Tresca. Infine prendere Strada Tresca.',
                'artista' => 'Pinguini Tattici Nucleari',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => 10000,
                'costo' => 20.00,
                'org_name' => 'Organizzatore 02',
                'descrizione' => 'I Pinguini Tattici Nucleari tornano live dopo più di un anno per il loro concerto a Bari. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 10],

            ['event_id'=> '8',
                'luogo' => 'Palermo, Stadio Renzo Barbera',
                'data'=> '2022-02-01',
                'ora'=>'18:00:00',
                'regione'=> 'Sicilia',
                'image_catalogo'=> '8.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'Autostrada A19 (Palermo - Catania), A20 (Palermo - Messina) o A29 (Palermo - Trapani). Uscire a Palermo e seguire il percorso seguente: viale Della Regione Siciliana, svincolo via Belgio, via Empedocle Restivo, via Alcide De Gasperi fino allo stadio Barbera.',
                'artista' => 'Sfera Ebbasta',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => 10000,
                'costo' => 30.00,
                'org_name' => 'Organizzatore 02',
                'descrizione' => 'Sfera Ebbasta torna live dopo più di un anno per il suo concerto a Palermo. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 10],

            ['event_id'=> '9',
                'luogo' => 'Pescara, Stadio Adriatico',
                'data'=> '2022-03-01',
                'ora'=>'18:00:00',
                'regione'=> 'Abruzzo',
                'image_catalogo'=> '9.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'Arrivando da Bologna: Autostrada A14 in direzione sud, uscire al casello PESCARA OVEST-CHIETI. Prendere la seconda strada a destra e imboccare il raccordo Autostradale Pescara-Chieti. Quindi dopo 6 km prendere la SS16/E80 in direzione FRANCAVILLA-FOGGIA. Seguire la segnaletica in direzione stadio. Arrivando da Bari: Autostrada A14 in direzione nord, uscire al casello PESCARA OVEST-CHIETI. Prendere la seconda strada a destra e imboccare il raccordo Autostradale Pescara-Chieti. Quindi dopo 6 km prendere la SS16/E80 in direzione FRANCAVILLA-FOGGIA. Seguire la segnaletica in direzione stadio. Arrivando da Roma: Autostrada A24 in direzione est, uscire al casello PESCARA OVEST-CHIETI-PESCARA CENTRO. Seguire le indicazioni per PESCARA e imboccare il raccordo Autostradale Pescara-Chieti. Quindi dopo 6 km prendere la SS16/E80 in direzione FRANCAVILLA-FOGGIA. Seguire la segnaletica in direzione stadio.',
                'artista' => 'Rovere',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => 10000,
                'costo' => 18.00,
                'org_name' => 'Organizzatore 03',
                'descrizione' => 'I Rovere tornano live dopo più di un anno per il loro concerto a Pescara. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 10],

            ['event_id'=> '10',
                'luogo' => 'Firenze, Stadio Artemio Franchi',
                'data'=> '2022-04-01',
                'ora'=>'18:00:00',
                'regione'=> 'Toscana',
                'image_catalogo'=> '10.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'In autobus, dal centro di Firenze (stazione Santa Maria Novella o Piazza San Marco) - Linee 7, 17 o 20 (nei giorni delle gare sono attivate corse supplementari). In treno, la fermata più vicina è quella di Firenze Campo di Marte (400 metri dallo stadio): all’uscita della stazione percorrere Largo Gennarelli fino al semaforo. Per chi arriva alla fermata di Firenze Santa Maria Novella, prendere un treno che si dirige verso la stazione Campo di Marte. In auto, per chi percorre l’autostrada A1 Milano-Napoli, uscire all’uscita Firenze Sud. Percorrere l’intero viadotto di Varlungo Marco Polo, quindi seguire le indicazioni “STADIO” presenti agli incroci. Distanza dall’uscita dell’autostrada: 4.6 km.',
                'artista' => 'Ultimo',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => 10000,
                'costo' => 28.00,
                'org_name' => 'Organizzatore 03',
                'descrizione' => 'Ultimo torna live dopo più di un anno per il suo concerto a Firenze. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 10],

            ['event_id'=> '11',
                'luogo' => 'Cagliari, Sardegna Arena',
                'data'=> '2022-05-01',
                'ora'=>'18:00:00',
                'regione'=> 'Sardegna',
                'image_catalogo'=> '11.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'Per chi proviene dal centro e nord della Sardegna l’itinerario più semplice è rappresentato dall’Asse Mediano di Scorrimento, imboccabile dalla s.s. 131. Le auto provenienti dalla parte orientale dell’isola possono costeggiare il Poetto e raggiungere facilmente i parcheggi dello stadio svoltando in prossimità del viale intitolato ai Campioni d’Italia 1969/1970. Dal centro città è invece consigliabile percorrere Viale Colombo e quindi Viale Salvatore Ferrara, giungendo al parcheggio “cuore” del vecchio Sant’Elia.',
                'artista' => 'Tedua',
                'biglietti_totali' => 10000,
                'biglietti_rimasti' => 10000,
                'costo' => 22.00,
                'org_name' => 'Organizzatore 01',
                'descrizione' => 'Tedua torna live dopo più di un anno per il suo concerto a Cagliari. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 10],

            ['event_id'=> '12',
                'luogo' => 'Ascoli Piceno, Stadio Cino e Lillo Del Duca',
                'data'=> '2022-06-01',
                'ora'=>'18:00:00',
                'regione'=> 'Marche',
                'image_catalogo'=> '12.jpg',
                'programma' => 'Ore 17:00 apertura cancelli. Ore 21:00 inizio apertura concerto. Ore 21:30 inizio concerto. Ore 23:00 fine concerto',
                'indicazioni' => 'In auto, uscita Ascoli Piceno Est dell’Ascoli-Mare, seguire le indicazioni “Stadio”; uscita Ascoli Piceno Ovest (consigliata per la tifoseria ospite), proseguire per Ascoli centro e imboccare la circonvallazione nord. In treno, dalla stazione ferroviaria di Ascoli Piceno è possibile raggiungerlo a piedi vista la vicinanza dell’impianto situato a circa 400 m. In aereo, gli aeroporti più vicini sono l’Aeroporto di Ancona-Falconara e l’Aeroporto di Pescara.',
                'artista' => 'Nerkias',
                'biglietti_totali' => 1000,
                'biglietti_rimasti' => 1000,
                'costo' => 5.00,
                'org_name' => 'Organizzatore 01',
                'descrizione' => 'I Nerkias tornano live dopo più di un anno per il loro concerto in Ascoli. Compra i tuoi biglietti qui su TicketWorld!',
                'percentuale_sconto' => 20,
                'giorni_sconto' => 10],


        ]);

        DB::table('faq')->insert([
            ['id'=>'1',
                'domanda'=>'Quali sono i criteri di ricerca dei prodotti in vendita applicabili?',
                'risposta'=> 'Dal sito TicketWorld è possibile effettuare una ricerca avanzata tramite la sezione "Filtri" nella pagina "CATALOGO".'
            ],

            ['id'=>'2', 'domanda'=>'E’ possibile avere l’annullamento e il rimborso del mio ordine di acquisto?',
                'risposta'=> 'Non è previsto il rimborso, né del prezzo dei Titoli di Ingresso né delle eventuali commissioni
            aggiuntive, nel caso di rinuncia da parte del cliente. L’unico caso previsto per consentire annullamenti e
            rimborsi è quello relativo ad un annullamento dell’evento stesso.'],
            ['id'=>'3', 'domanda'=>'Il concerto non si è più svolto. Cosa devo fare per avere il rimborso del biglietto?',
                'risposta'=> 'Data e orario dell’evento potrebbero subire variazioni. Consigliamo di monitorare il nostro sito prima
            dell\'evento. In questo caso non sono previsti rimborsi. Mentre nel caso di annullo o posticipo dell’evento
            le modalità verranno comunicate dall’organizzatore e pubblicate sul nostro sito.'],
            ['id'=>'4', 'domanda'=>'Come avviene il rimborso?',
                'risposta'=> 'Per gli acquisti effettuati tramite Internet e Call Center l’assistenza provvederà a richiedere lo
            storno sullo stesso metodo di pagamento utilizzato in fase di acquisto; questo sarà reso disponibile in base
            ai tempi tecnici previsti dell’Istituto che ha emesso la carta con la quale è stato effettuato il pagamento
            dell’ordine.']
        ]);

        // Biglietti evento 1
        for ($i=0; $i < 126; $i++) {
            DB::table('tickets')->insert([
                'id_evento' => 1,
                'user_id' => 4,
                'costo_biglietto' => 20.00,
            ]);
        }

        // Biglietti evento 2
        for ($i=0; $i < 42; $i++) {
            DB::table('tickets')->insert([
                'id_evento' => 2,
                'user_id' => 5,
                'costo_biglietto' => 19.20,
            ]);
        }

        // Biglietti evento 3
        for ($i=0; $i < 28; $i++) {
            DB::table('tickets')->insert([
                'id_evento' => 3,
                'user_id' => 6,
                'costo_biglietto' => 18.40,
            ]);
        }

    }
}
